package string;

public class FindTheDifference {

    //389. Find the Difference
    //Easy
    //You are given two strings s and t.
    //
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //
    //Return the letter that was added to t.

    //Related Topics
    //Hash Table
    //String
    //Bit Manipulation
    //Sorting


    public static char findTheDifference(String s, String t) {

        int sSum = 0;
        int tSum = 0;

        for (int i = t.length() - 1; i >= 0; i--) {
            if (i != 0) {
                sSum += s.charAt(i - 1);
            }
            tSum += t.charAt(i);
        }

        tSum -= sSum;
        return (char) tSum;
    }


}
